# -----------------------------
# Target Code Generated by Mini Compiler
# Source Language: Mini Language
# Target Language: Python
# -----------------------------

def main():
    # Variable declarations
    a = 5
    b = 10

    # Arithmetic operations
    c = a + b
    d = c * 2

    # Output
    print("Value of a:", a)
    print("Value of b:", b)
    print("Sum (c):", c)
    print("Final result (d):", d)


# Program execution starts here
if __name__ == "__main__":
    main()
